name: 'Remind by forgetting curve'
description: 'Remind by forgetting curve'
inputs:
  repo-token:
    description: 'repo token'
    required:tru
    default: ''
  labels:
    description: 'labels to remind'
    required: false
    default: '["need-to-remind"]'
  remind-days:
    description: 'remind days'
    required: false
    default: '[1, 3, 10, 30, 90]'
  message:
    description: 'message to remind the issue'
    required: false
    default: "It\' s time to remember this issue!"
runs:
  using: 'node16'
  main: 'index.js'
